# Generated by Django 6.1.1 on 2026-10-05 09:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('airport_buffer', 'Airport Buffer'), ('user_drawn', 'User Drawn')], default='user_drawn', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geofences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(max_length=6)),
                ('event', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], max_length=5)),
                ('ts', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='geofencing.geofence')),
            ],
            options={
                'db_table': 'geofence_events',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['ts'], name='geofence_events_ts_idx'), models.Index(fields=['geofence', 'ts'], name='geofence_events_fence_ts_idx')],
            },
        ),
    ]
