# Generated by Django 6.1.1 on 2026-10-05 09:42

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('icao24', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('callsign', models.CharField(blank=True, max_length=8, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.SmallIntegerField(blank=True, null=True)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'aircraft',
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('ts', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('baro_altitude', models.FloatField(blank=True, null=True)),
                ('geo_altitude', models.FloatField(blank=True, null=True)),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('vertical_rate', models.FloatField(blank=True, null=True)),
                ('on_ground', models.BooleanField(db_default=False)),
                ('squawk', models.CharField(blank=True, max_length=4, null=True)),
                ('source', models.CharField(choices=[('live', 'Live'), ('replay', 'Replay'), ('synthetic', 'Synthetic')], db_default='live', max_length=10)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icao24', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'positions',
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['ts'], name='positions_ts_brin')],
                'constraints': [models.UniqueConstraint(fields=('icao24', 'ts'), name='positions_icao24_ts_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AircraftLatest',
            fields=[
                ('ts', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('baro_altitude', models.FloatField(blank=True, null=True)),
                ('geo_altitude', models.FloatField(blank=True, null=True)),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('vertical_rate', models.FloatField(blank=True, null=True)),
                ('on_ground', models.BooleanField(db_default=False)),
                ('squawk', models.CharField(blank=True, max_length=4, null=True)),
                ('source', models.CharField(choices=[('live', 'Live'), ('replay', 'Replay'), ('synthetic', 'Synthetic')], db_default='live', max_length=10)),
                ('aircraft', models.OneToOneField(db_column='icao24', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracking.aircraft')),
            ],
            options={
                'verbose_name_plural': 'aircraft latest',
                'db_table': 'aircraft_latest',
                'indexes': [models.Index(fields=['ts'], name='aircraft_latest_ts_idx')],
            },
        ),
    ]
