# Generated by Django 6.1.1 on 2026-10-05 09:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=16, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True)),
                ('gps_code', models.CharField(blank=True, max_length=8, null=True)),
                ('municipality', models.CharField(blank=True, max_length=128, null=True)),
                ('iso_country', models.CharField(blank=True, max_length=2)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'airports',
                'ordering': ['ident'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('iso_code', models.CharField(max_length=8, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'provinces',
                'ordering': ['name'],
            },
        ),
    ]
